### PR TITLE
Added transfer api Endpoints

### PR DESCRIPTION
**Pull request by mohdsameer**

### CODE REVIEW

**Comment by somentelucas** [comment]
references #58 
closes #58

**Comment by bressani** [comment]
@mohdsameer Hello!

Could you add unit tests and update the README, please?

It's also missing the list feature for transfers (https://dev.moip.com.br/v2.0/reference#listar-todas-transferências-1).

Thank you!

**Comment by Lucasfr10** [comment]
Someone can resolve this conflict please? We are in need of this feature.

**Comment by somentelucas** [comment]
Hi @Lucasfr10, we are about to release a new version of the SDK next week that includes the transfer endpoints. This PR will not be merged, but the feature is already available under the develop branch, we just need to do the release.

You can check it here: https://github.com/moip/moip-sdk-ruby/tree/develop#transfer%C3%AAncia

**Comment by jorgedjr21** [comment]
@somentelucas what about the new version of the SDK, any news?

**Pull request closed without merging**
